### ISSUE TITLE
blank screen on real iron

### ISSUE THREAD

**Issue by TurBoss** [GenesisFan64/FamiDrive-MD#1]
hello, thanks for this awesome project

 I tried to build some games but I only managed to play those on gens
on mega-drive 1800-16 I get a blank screen

tested games:
ballon flight
super mario
popeye

tried pcb with eproms and a clonic everdrive

Thanks

**Comment by GenesisFan64** [comment]
Hey, hello.
Being honest here, this was only for researching. The original emulator isn't mine, it is by Mairtrus but I wanted to see If I could improve it: I added another mapper and fixed some things (but then I broke other stuff...)

But I'm not working on this anymore, sorry.

**Comment by TurBoss** [comment]
oh okay

thanks
